name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: ps2dev/ps2toolchain:latest
    steps:
    - uses: actions/checkout@v2
    - name: instalação dos apps de compilação
      run: |
       apk add -y build-base git bash
